### ISSUE TITLE
魅夜黑主题

### ISSUE THREAD

**Issue by hpoill** [fancyLv/MapDownloader#1]
魅夜黑主题，怎么修改参数获取

**Comment by fancyLv** [comment]
自定义style参考：t:water|e:all|c:#246386ff,t:highway|e:g.f|c:#000000,t:highway|e:g.s|c:#147a92,t:arterial|e:g.f|c:#000000,t:arterial|e:g.s|c:#0b3d51,t:local|e:g|c:#000000,t:land|e:g.f|c:#044c71ff,t:railway|e:g.f|c:#000000,t:railway|e:g.s|c:#08304b,t:subway|e:g|l:-70,t:building|e:g.f|c:#000000,t:all|e:l.t.f|c:#857f7f,t:all|e:l.t.s|c:#000000,t:building|e:g|c:#022338,t:green|e:g|c:#0b385fff,t:boundary|e:all|c:#1e1c1c,t:manmade|e:g|c:#022338,t:poi|e:all|v:off,t:all|e:l.i|v:off,t:road|e:g.f|v:on|c:#326081ff|l:-69,t:land|e:g.f|c:#012f50ff|l:3|s:20,t:road|e:g.s|v:on|c:#133b6eff|l:4,t:manmade|e:l|v:on,t:administrative|e:l.t.f|v:on|c:#90d7fbff|l:-51,t:road|e:g.f|c:#09485eff，直接使用百度地图提供的样式模板暂未实现，需要新增参数项customid
